<#
.SYNOPSIS
  Builds the MineCanon native Windows launcher (MineCanon.exe with a bundled Java runtime).

.DESCRIPTION
  Compiles launcher\src, runs SelfTest, generates the icon, packages a private Java runtime
  with jlink, and creates launcher\bin\MineCanon\MineCanon.exe with jpackage.
  Also writes MineCanon.lnk to the repository root so the app can be double-clicked from there.
  Requires a JDK 17+ that includes jpackage (JAVA_HOME or javac on PATH). No downloads.
#>
param(
    [switch]$SkipTests,
    [switch]$DesktopShortcut,
    [string]$WorkDir
)
$ErrorActionPreference = 'Stop'
$launcher = $PSScriptRoot
$root = Split-Path $launcher -Parent
$forgeName = 'forge-1.20.1-47.4.26-installer.jar'
$forgeSha = '138961BC2A5F085CED0B5DB2CD72C6CAAD20B25E22BCDCCD031B4FC9182E8186'
$forge = Join-Path $root "mods-1.20.1-base\$forgeName"
# WorkDir is restricted to build* folders under the launcher directory or the user temp folder,
# so cleanup can never touch caller data elsewhere. The default is outside any synced folder
# (Desktop\OneDrive etc.), because jlink/jpackage stall there when the sync engine holds new files.
if ($WorkDir) {
    $WorkDirFull = [IO.Path]::GetFullPath((Join-Path (Get-Location) $WorkDir))
    $insideLauncher = $WorkDirFull.StartsWith($launcher, [StringComparison]::OrdinalIgnoreCase)
    $insideTemp = $WorkDirFull.StartsWith([IO.Path]::GetFullPath($env:TEMP), [StringComparison]::OrdinalIgnoreCase)
    $leafIsBuild = (Split-Path $WorkDirFull -Leaf) -like 'build*'
    if (-not (($insideLauncher -or $insideTemp) -and $leafIsBuild)) { throw 'WorkDir must be a build* folder inside the launcher directory or the user temp folder.' }
    $work = $WorkDirFull
} else { $work = Join-Path $env:TEMP 'minecanon-build' }
$bin = Join-Path $launcher 'bin'
$app = Join-Path $bin 'MineCanon'
$exe = Join-Path $app 'MineCanon.exe'
$marker = '.minecanon-generated'

function Invoke-Tool([string]$tool, [string[]]$arguments, [string]$failure) {
    & (Join-Path $jdk "bin\$tool.exe") @arguments
    if ($LASTEXITCODE -ne 0) { throw $failure }
}

# --- JDK -------------------------------------------------------------------
$jdk = $null
if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME 'bin\jpackage.exe'))) {
    $jdk = $env:JAVA_HOME
} else {
    $javac = Get-Command javac.exe -ErrorAction SilentlyContinue
    if ($javac) { $jdk = Split-Path (Split-Path $javac.Source -Parent) -Parent }
}
if (-not $jdk) { throw 'Install a JDK 17 or newer with jpackage, or set JAVA_HOME to it.' }
foreach ($tool in 'javac', 'java', 'jar', 'jlink', 'jpackage') {
    if (-not (Test-Path (Join-Path $jdk "bin\$tool.exe"))) { throw "Missing JDK tool: $tool (in $jdk)" }
}
Write-Host "JDK: $jdk"

# --- Inputs ----------------------------------------------------------------
if (-not (Test-Path $forge)) { throw "Forge installer not found: $forge" }
if ((Get-Item $forge).Length -lt 1MB) { throw "Forge installer looks like a Git LFS pointer. Run 'git lfs pull' first." }
if ((Get-FileHash $forge -Algorithm SHA256).Hash -ne $forgeSha) { throw 'Forge installer SHA-256 does not match the pinned 47.4.26 installer.' }
foreach ($required in 'src', 'assets\world.png', 'assets\ages.png', 'assets\dossier-sha256.properties', 'dossier') {
    if (-not (Test-Path (Join-Path $launcher $required))) { throw "Missing launcher input: launcher\$required" }
}
if ((Test-Path $app) -and -not (Test-Path (Join-Path $app $marker))) {
    throw "$app exists but was not generated by this script. Move it aside and retry."
}

# --- Clean work area -------------------------------------------------------
if (Test-Path $work) { Remove-Item -Recurse -Force $work }
$classes = Join-Path $work 'classes'
$jarClasses = Join-Path $work 'jar-classes'
$stage = Join-Path $work 'input'
New-Item -ItemType Directory -Force $classes, $jarClasses, $stage | Out-Null

# The packaged app folder doubles as the "bundle" directory the launcher reads at runtime.
Copy-Item $forge $stage
$forge = Join-Path $stage $forgeName
Copy-Item (Join-Path $launcher 'dossier') $stage -Recurse

# --- Compile ---------------------------------------------------------------
Write-Host 'Compiling...'
$sources = (Get-ChildItem (Join-Path $launcher 'src') -Filter *.java).FullName
$ErrorActionPreference = 'Continue'
$javacOut = & (Join-Path $jdk 'bin\javac.exe') (@('--release', '17', '-encoding', 'UTF-8', '-cp', $forge, '-d', $classes) + $sources) 2>&1 | ForEach-Object { "$_" }
$javacExit = $LASTEXITCODE
$ErrorActionPreference = 'Stop'
$javacOut | Write-Host
if ($javacExit -ne 0) {
    # Restricted sandboxes deny Path.toRealPath, which javac only needs while closing jar handles.
    $compiled = $sources | ForEach-Object { Test-Path (Join-Path $classes ([IO.Path]::GetFileNameWithoutExtension($_) + '.class')) }
    $onlyCloseError = ($javacOut -match '\.java:\d+: error:').Count -eq 0 -and ($javacOut -match 'Cannot close compiler resources')
    if (-not ($onlyCloseError -and ($compiled -notcontains $false))) { throw 'Compilation failed.' }
    Write-Warning 'javac could not release the Forge jar handle, but every class compiled; continuing.'
}
Copy-Item (Join-Path $launcher 'assets') $classes -Recurse
$classpath = "$classes;$forge"

if (-not $SkipTests) {
    Write-Host 'Running SelfTest...'
    Invoke-Tool 'java' @('-Djava.awt.headless=true', '-cp', $classpath, 'SelfTest', $stage) 'SelfTest failed.'
}

# --- In-game hub mod (v2) ----------------------------------------------------
# Ships in the app folder; the launcher auto-installs it into every age instance
# and writes -Dminecanon.age into the profile. Staged after SelfTest so the
# test bundle stays without it, matching a first run.
$modJar = Join-Path $root 'mod\jar\minecanon-1.0.0.jar'
if (Test-Path $modJar) { Copy-Item $modJar $stage } else { Write-Warning 'mod\jar\minecanon-1.0.0.jar not found; the launcher will run without auto-installing the in-game hub mod.' }

$icon = Join-Path $work 'MineCanon.ico'
Invoke-Tool 'java' @('-Djava.awt.headless=true', '-cp', $classpath, 'MineCanonIcon', $icon) 'Icon creation failed.'

# --- JAR -------------------------------------------------------------------
Copy-Item (Join-Path $classes '*') $jarClasses -Recurse -Exclude 'SelfTest*.class'
$manifest = Join-Path $work 'MANIFEST.MF'
Set-Content $manifest "Main-Class: MineCanonLauncher`r`nClass-Path: $forgeName`r`n" -Encoding ASCII
Invoke-Tool 'jar' @('--create', '--file', (Join-Path $stage 'MineCanon.jar'), '--manifest', $manifest, '-C', $jarClasses, '.') 'JAR creation failed.'

# --- Runtime + native image ------------------------------------------------
# The bundled runtime also runs the Forge installer, which needs TLS, XML, logging, etc.
Write-Host 'Creating Java runtime...'
$modules = @('java.se', 'jdk.unsupported', 'jdk.zipfs', 'jdk.charsets', 'jdk.localedata', 'jdk.crypto.cryptoki', 'jdk.accessibility')
if (Test-Path (Join-Path $jdk 'jmods\jdk.crypto.ec.jmod')) { $modules += 'jdk.crypto.ec' }
$runtime = Join-Path $work 'runtime'
Invoke-Tool 'jlink' @('--add-modules', ($modules -join ','), '--strip-debug', '--no-header-files', '--no-man-pages', '--output', $runtime) 'Runtime creation failed.'

Invoke-Tool 'javac' @('--release', '17', '-d', $classes, (Join-Path $launcher 'ForgeRuntimeCheck.java')) 'Runtime check compilation failed.'
& (Join-Path $runtime 'bin\java.exe') '-Djava.awt.headless=true' -cp "$classes;$forge" ForgeRuntimeCheck
if ($LASTEXITCODE -ne 0) { throw 'Bundled runtime cannot load the Forge install profile.' }

# Package into a staging folder inside the work area first (never the synced launcher folder),
# then swap: a failed packaging run never destroys the previous working app.
$staging = Join-Path $work 'packaged'
if (Test-Path $staging) { Remove-Item -Recurse -Force $staging }
New-Item -ItemType Directory -Force $staging | Out-Null
Write-Host 'Packaging MineCanon.exe...'
Invoke-Tool 'jpackage' @('--type', 'app-image', '--name', 'MineCanon', '--dest', $staging,
    '--input', $stage, '--main-jar', 'MineCanon.jar', '--main-class', 'MineCanonLauncher',
    '--runtime-image', $runtime, '--icon', $icon, '--vendor', 'John Matukutire',
    '--description', 'Mine Canon World desktop launcher', '--app-version', '2.0.0') 'Native packaging failed.'
if (Test-Path $app) {
    Write-Host 'Replacing previous build (close MineCanon first)...'
    Remove-Item -Recurse -Force $app
}
New-Item -ItemType Directory -Force $bin | Out-Null
Move-Item (Join-Path $staging 'MineCanon') $app
New-Item -ItemType File (Join-Path $app $marker) | Out-Null

# --- Shortcuts -------------------------------------------------------------
$shell = New-Object -ComObject WScript.Shell
$targets = @(Join-Path $root 'MineCanon.lnk')
if ($DesktopShortcut) { $targets += Join-Path ([Environment]::GetFolderPath('Desktop')) 'MineCanon.lnk' }
foreach ($path in $targets) {
    $link = $shell.CreateShortcut($path)
    $link.TargetPath = $exe
    $link.WorkingDirectory = $app
    $link.IconLocation = "$exe,0"
    $link.Description = 'MineCanon - John Matukutire | Mine Canon World'
    $link.Save()
    Write-Host "Shortcut: $path"
}
Write-Host "Built: $exe"
