import javax.swing.*;
import java.awt.*;
import java.awt.geom.*;
import java.util.*;

final class CanonPanels {
    static final class Classification extends JPanel {
        final LauncherUI ui;final JLabel heading,bstLabel,rank,band,assessment;final JComboBox<String> nature;final JSpinner bst;
        Classification(LauncherUI ui){this.ui=ui;setLayout(null);setBackground(LauncherUI.PANEL);setBorder(BorderFactory.createLineBorder(LauncherUI.LINE));
            heading=ui.label("CLASSIFICATION",18,LauncherUI.TEXT);heading.setFont(LauncherUI.serif(20));heading.setToolTipText("Timeline schema Hₜ = [E, K, I, T, B, C]; source classification uses draft BST bands");add(heading);
            nature=new JComboBox<>(new String[]{"Hunter","Monster","Hybrid"});ui.styleCombo(nature);nature.setToolTipText("Draft identity category; independent of BST rank");add(nature);
            bstLabel=ui.label("Σ BST",14,LauncherUI.MUTED);add(bstLabel);bst=new JSpinner(new SpinnerNumberModel(410,0,9999,10));bst.setFont(LauncherUI.sans(18));bst.setBackground(LauncherUI.PANEL);bst.setBorder(BorderFactory.createLineBorder(LauncherUI.LINE));JFormattedTextField number=((JSpinner.DefaultEditor)bst.getEditor()).getTextField();number.setBackground(LauncherUI.PANEL);number.setForeground(LauncherUI.TEXT);number.setCaretColor(LauncherUI.ORANGE);number.setBorder(BorderFactory.createEmptyBorder(3,8,3,8));bst.setToolTipText("Explore the draft rank ladder; this does not alter Minecraft entities");add(bst);
            rank=ui.label("",17,LauncherUI.TEXT);band=ui.label("",13,LauncherUI.MUTED);assessment=ui.label("",12,LauncherUI.SAGE);add(rank);add(band);add(assessment);bst.addChangeListener(e->refresh());nature.addActionListener(e->refresh());refresh();
        }
        void refresh(){int value=(int)bst.getValue();rank.setText(CanonModel.rank(value)+" · draft rank");band.setText(CanonModel.band(ui.service.selected()));assessment.setText(CanonModel.assessment(ui.service.selected(),value));}
        public void doLayout(){int w=getWidth();heading.setBounds(22,12,w-30,30);nature.setBounds(22,54,Math.min(w<650?150:170,w/3),39);bstLabel.setBounds(22,111,48,30);bst.setBounds(70,107,98,39);int rx=w<650?192:230;rank.setBounds(rx,58,w-rx-12,28);band.setBounds(rx,96,w-rx-12,26);assessment.setBounds(rx,132,w-rx-12,24);}
    }
    static final class Lineage extends JPanel {
        final LauncherUI ui;final JButton[] nodes=new JButton[8];final String[] names={"Canon Field","Breath","Resonance","Bending","Relics","Chakra","Nen","Cursed Energy"};
        final Color[] colors={new Color(218,184,115),new Color(244,131,89),new Color(107,182,247),new Color(119,210,226),new Color(185,134,232),new Color(224,157,224),new Color(136,212,161),new Color(187,140,244)};
        final int[] ages={-1,0,1,0,1,2,3,4};
        Lineage(LauncherUI ui){this.ui=ui;setOpaque(false);setLayout(null);for(int i=0;i<nodes.length;i++){final int ix=i;nodes[i]=new JButton(names[i]){protected void paintComponent(Graphics gg){Graphics2D g=(Graphics2D)gg.create();LauncherUI.quality(g);Color c=colors[ix];g.setColor(new Color(c.getRed()/9,c.getGreen()/9,c.getBlue()/9));g.fillRoundRect(0,0,getWidth(),getHeight(),6,6);g.setColor(c);g.setStroke(new BasicStroke(1.2f));g.drawRoundRect(1,1,getWidth()-3,getHeight()-3,6,6);g.setFont(new Font("Serif",Font.PLAIN,getWidth()<120?14:17));LauncherUI.center(g,names[ix],getWidth(),getHeight()/2+6);if(getModel().isRollover()||hasFocus()){g.drawRoundRect(4,4,getWidth()-9,getHeight()-9,4,4);}g.dispose();}};nodes[i].setContentAreaFilled(false);nodes[i].setBorderPainted(false);nodes[i].setFocusPainted(false);nodes[i].setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));nodes[i].setToolTipText(i==0?"Shared fictional source; graph edges are a proposed interpretation":"Select "+LauncherService.NAMES[ages[i]]+" instance");nodes[i].addActionListener(e->{if(ages[ix]>=0)ui.select(ages[ix]);else ui.info("The Canon Field is the shared fictional source.\nThis branching diagram is a proposed synthesis of your dossiers,\nnot an established biological phylogeny or a verified mathematical model.");});add(nodes[i]);}}
        int graphHeight(){return Math.max(355,(int)(getHeight()*.62));}
        public void doLayout(){int w=getWidth(),gh=graphHeight(),nw=(w-65)/2,nh=43,step=(gh-136)/4;int cx=(w-nw)/2,lx=25,rx=w-nw-25;nodes[0].setBounds(cx,86,nw,nh);nodes[1].setBounds(lx,86+step,nw,nh);nodes[2].setBounds(rx,86+step,nw,nh);nodes[3].setBounds(lx,86+step*2,nw,nh);nodes[4].setBounds(rx,86+step*2,nw,nh);nodes[5].setBounds(cx,86+step*3,nw,nh);nodes[6].setBounds(lx,86+step*4,nw,nh);nodes[7].setBounds(rx,86+step*4,nw,nh);}
        void line(Graphics2D g,int from,int to){Rectangle a=nodes[from].getBounds(),b=nodes[to].getBounds();double x1=a.getCenterX(),y1=a.getMaxY(),x2=b.getCenterX(),y2=b.getY();g.draw(new CubicCurve2D.Double(x1,y1,x1,(y1+y2)/2,x2,(y1+y2)/2,x2,y2));g.fill(new Polygon(new int[]{(int)x2-3,(int)x2+3,(int)x2},new int[]{(int)y2-5,(int)y2-5,(int)y2},3));}
        protected void paintComponent(Graphics gg){Graphics2D g=(Graphics2D)gg.create();LauncherUI.quality(g);int w=getWidth(),h=getHeight(),gh=graphHeight();g.setColor(LauncherUI.PANEL);g.fillRoundRect(0,0,w,gh+8,8,8);g.setColor(LauncherUI.LINE);g.drawRoundRect(0,0,w-1,gh+8,8,8);g.setColor(LauncherUI.TEXT);g.setFont(LauncherUI.serif(22));g.drawString("POWER LINEAGE",20,34);g.setFont(LauncherUI.sans(12));g.setColor(LauncherUI.MUTED);g.drawString("Canon Field / proposed model",20,58);g.setColor(new Color(210,193,149));g.setStroke(new BasicStroke(1.4f));for(int[] e:new int[][]{{0,1},{0,2},{1,3},{2,4},{3,5},{4,5},{5,6},{5,7}})line(g,e[0],e[1]);
            int vy=gh+20,vh=Math.min(181,h-vy-82);g.setColor(LauncherUI.PANEL);g.fillRoundRect(0,vy,w,vh,8,8);g.setColor(LauncherUI.LINE);g.drawRoundRect(0,vy,w-1,vh,8,8);g.setColor(LauncherUI.TEXT);g.setFont(LauncherUI.serif(20));g.drawString("VERIFICATION",20,vy+30);
            boolean hash=!ui.checks.isEmpty()&&ui.checks.get(0).pass();status(g,"Installer SHA-256",hash?"Match":"Check failed",hash,vy+55,w);status(g,"Forge profile",ui.service.forgeInstalled()?"Detected":"Setup required",ui.service.forgeInstalled(),vy+55+(vh-60)/3,w);status(g,"Formal claims","Review needed",false,vy+55+2*(vh-60)/3,w);
            int ly=vy+vh+13;if(h-ly>50){g.setColor(LauncherUI.PANEL);g.fillRoundRect(0,ly,w,h-ly,8,8);g.setColor(LauncherUI.TEXT);g.setFont(LauncherUI.serif(16));g.drawString("BOOT LOG",20,ly+25);g.setFont(new Font("Monospaced",Font.PLAIN,w<380?10:11));g.setColor(LauncherUI.MUTED);g.drawString("[LORE] The Canon Field stirs.",20,ly+49);if(h-ly>78)g.drawString("[LOCAL] "+LauncherService.NAMES[ui.service.selected()],20,ly+71);}
            g.dispose();
        }
        void status(Graphics2D g,String label,String value,boolean pass,int y,int w){g.setColor(pass?LauncherUI.SAGE:LauncherUI.ORANGE);g.fillOval(19,y-10,8,8);g.setFont(LauncherUI.sans(w<390?11:13));g.drawString(value,w-g.getFontMetrics().stringWidth(value)-18,y);g.setColor(LauncherUI.TEXT);g.drawString(label,38,y);}
    }
    static JComponent verification(LauncherUI ui){
        JPanel root=ui.panel();root.setLayout(new BorderLayout(0,14));root.add(ui.note("Runtime checks are measured locally. Dossier arithmetic checks are scoped to the cited table. Formal claims remain unverified. Glyphs: Σ (budget), Φ (pressure), Hₜ (timeline)."),BorderLayout.NORTH);
        JPanel rows=ui.panel();rows.setLayout(new GridLayout(ui.checks.size(),1,0,8));
        for(CanonModel.Check check:ui.checks){JPanel row=new JPanel(new BorderLayout(12,3));row.setBackground(LauncherUI.PANEL);row.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(LauncherUI.LINE),BorderFactory.createEmptyBorder(10,15,10,15)));JLabel label=ui.label((check.pass()?"●  ":"◆  ")+check.name(),16,LauncherUI.TEXT);row.add(label,BorderLayout.NORTH);JTextArea detail=ui.note(check.detail());detail.setFont(LauncherUI.sans(12));row.add(detail,BorderLayout.CENTER);row.add(ui.label(check.status(),12,check.pass()?LauncherUI.SAGE:LauncherUI.ORANGE),BorderLayout.EAST);rows.add(row);}
        rows.setPreferredSize(new Dimension(650,ui.checks.size()*102));JScrollPane sc=new JScrollPane(rows);sc.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);sc.setBorder(null);sc.getViewport().setOpaque(false);sc.setOpaque(false);root.add(sc,BorderLayout.CENTER);
        JPanel actions=ui.panel();actions.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));LauncherUI.ActionButton rerun=new LauncherUI.ActionButton("Run verification",true);rerun.setPreferredSize(new Dimension(220,45));rerun.addActionListener(e->{ui.showPage("Verification");});actions.add(rerun);actions.add(Box.createHorizontalStrut(12));LauncherUI.ActionButton docs=new LauncherUI.ActionButton("Open source dossier",false);docs.setPreferredSize(new Dimension(230,45));docs.addActionListener(e->{try{ui.service.openFolder(ui.service.bundle.resolve("dossier"));}catch(Exception ex){ui.error(ex);}});actions.add(docs);root.add(actions,BorderLayout.SOUTH);return root;
    }
    static JComponent bootLog(LauncherUI ui){
        JPanel p=ui.panel();p.setLayout(new BorderLayout(0,16));p.add(ui.note("LORE entries are narrative flavor. LOCAL entries describe actual launcher activity. No gameplay or world-server connection is implied. This view shows the current session."),BorderLayout.NORTH);JTextArea log=new JTextArea(String.join("\n\n",ui.canon.log));log.setEditable(false);log.setLineWrap(true);log.setWrapStyleWord(true);log.setFont(new Font("Monospaced",Font.PLAIN,14));log.setBackground(LauncherUI.PANEL);log.setForeground(LauncherUI.TEXT);log.setBorder(BorderFactory.createEmptyBorder(20,20,20,20));JScrollPane scroll=new JScrollPane(log);scroll.setBorder(BorderFactory.createLineBorder(LauncherUI.LINE));p.add(scroll,BorderLayout.CENTER);LauncherUI.ActionButton b=new LauncherUI.ActionButton("Open log folder",false);b.setPreferredSize(new Dimension(220,45));b.addActionListener(e->{try{ui.service.openFolder(ui.service.home);}catch(Exception ex){ui.error(ex);}});JPanel bottom=ui.panel();bottom.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));bottom.add(b);p.add(bottom,BorderLayout.SOUTH);return p;
    }
}
